### ISSUE TITLE
[help wanted]

### ISSUE THREAD

**Issue by Joshbm787** [extatent/phoenix-nuker#5]
VirusTotal pings a few viruses, likely false flags but was curious about this one in particular as it seems to not often false ping  

Trojan:Win32/Wacatac.B!ml 

Thank you in advance my friend

**Comment by extatent** [comment]
Internet is your friend. According to [Microsoft](https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?Name=Trojan:Win32/Wacatac.B!ml), this threat can perform a number of actions of a malicious hacker's choice on your PC. It is a false positive. It's normal for such a program to trigger such detection.
