### ISSUE TITLE
what do i need to open the file?

### ISSUE THREAD

**Issue by Kalinetic** [extatent/Phoenix-Nuker#51]
What software do i need??? because i cant open it ): please help

**Comment by Iknack** [comment]
deleted it
its a trojan horse

**Comment by Iknack** [comment]
use lithium nuker its been proven safe heres a reuploaded version https://github.com/Aids-dev/Lithium-Nuker-Autism

**Comment by Kalinetic** [comment]
Thank you

**Comment by Kalinetic** [comment]
i downloaded the file and it had had a link to a picture and im confused

**Comment by Iknack** [comment]
download it from the releases
